# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Video.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogVideo(object):
    def setupUi(self, dialogVideo):
        dialogVideo.setObjectName("dialogVideo")
        dialogVideo.resize(918, 604)
        dialogVideo.setStyleSheet("background-color: rgb(246, 255, 246);")
        self.label = QtWidgets.QLabel(dialogVideo)
        self.label.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(dialogVideo)
        self.checkBox.setGeometry(QtCore.QRect(30, 110, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(dialogVideo)
        self.checkBox_2.setGeometry(QtCore.QRect(280, 110, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(dialogVideo)
        self.checkBox_3.setGeometry(QtCore.QRect(100, 110, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(dialogVideo)
        self.checkBox_4.setGeometry(QtCore.QRect(180, 110, 91, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_2 = QtWidgets.QLabel(dialogVideo)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialogVideo)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialogVideo)
        self.label_4.setGeometry(QtCore.QRect(460, 140, 151, 16))
        self.label_4.setObjectName("label_4")
        self.btnAtras = QtWidgets.QPushButton(dialogVideo)
        self.btnAtras.setGeometry(QtCore.QRect(20, 520, 75, 23))
        self.btnAtras.setObjectName("btnAtras")
        self.btnSalir = QtWidgets.QPushButton(dialogVideo)
        self.btnSalir.setGeometry(QtCore.QRect(800, 40, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        self.pushButton = QtWidgets.QPushButton(dialogVideo)
        self.pushButton.setGeometry(QtCore.QRect(470, 510, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(dialogVideo)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 510, 41, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(dialogVideo)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 510, 41, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(dialogVideo)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 510, 71, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.openOriginal = QtWidgets.QOpenGLWidget(dialogVideo)
        self.openOriginal.setGeometry(QtCore.QRect(10, 170, 431, 331))
        self.openOriginal.setObjectName("openOriginal")
        self.openReconocimiento = QtWidgets.QOpenGLWidget(dialogVideo)
        self.openReconocimiento.setGeometry(QtCore.QRect(450, 170, 431, 331))
        self.openReconocimiento.setObjectName("openReconocimiento")

        self.retranslateUi(dialogVideo)
        QtCore.QMetaObject.connectSlotsByName(dialogVideo)

    def retranslateUi(self, dialogVideo):
        _translate = QtCore.QCoreApplication.translate
        dialogVideo.setWindowTitle(_translate("dialogVideo", "Reconocimiento de Objetos"))
        self.label.setText(_translate("dialogVideo", "Video/Cámara"))
        self.checkBox.setText(_translate("dialogVideo", "Círculos"))
        self.checkBox_2.setText(_translate("dialogVideo", "Cuadrado"))
        self.checkBox_3.setText(_translate("dialogVideo", "Triángulos"))
        self.checkBox_4.setText(_translate("dialogVideo", "Rectángulos"))
        self.label_2.setText(_translate("dialogVideo", "Reconocimiento de Objetos"))
        self.label_3.setText(_translate("dialogVideo", "Figura/as a captar:"))
        self.label_4.setText(_translate("dialogVideo", "Reconocimiento de objetos"))
        self.btnAtras.setText(_translate("dialogVideo", "Atrás"))
        self.btnSalir.setText(_translate("dialogVideo", "Salir"))
        self.pushButton.setText(_translate("dialogVideo", "Empezar"))
        self.pushButton_2.setText(_translate("dialogVideo", "Pausar"))
        self.pushButton_3.setText(_translate("dialogVideo", "Detener"))
        self.pushButton_5.setText(_translate("dialogVideo", "Descargar"))
