# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogPrincipal(object):
    def setupUi(self, dialogPrincipal):
        dialogPrincipal.setObjectName("dialogPrincipal")
        dialogPrincipal.resize(625, 525)
        dialogPrincipal.setStyleSheet("background-color: rgb(246, 255, 246);")
        self.label = QtWidgets.QLabel(dialogPrincipal)
        self.label.setGeometry(QtCore.QRect(130, 20, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialogPrincipal)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialogPrincipal)
        self.label_3.setGeometry(QtCore.QRect(210, 150, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialogPrincipal)
        self.label_4.setGeometry(QtCore.QRect(120, 120, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnSalir = QtWidgets.QPushButton(dialogPrincipal)
        self.btnSalir.setGeometry(QtCore.QRect(50, 460, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        self.btnSiguiente = QtWidgets.QPushButton(dialogPrincipal)
        self.btnSiguiente.setGeometry(QtCore.QRect(500, 450, 75, 23))
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.btnVideo = QtWidgets.QPushButton(dialogPrincipal)
        self.btnVideo.setGeometry(QtCore.QRect(540, 250, 75, 23))
        self.btnVideo.setObjectName("btnVideo")
        self.lblRuta = QtWidgets.QLabel(dialogPrincipal)
        self.lblRuta.setGeometry(QtCore.QRect(330, 290, 171, 16))
        self.lblRuta.setObjectName("lblRuta")
        self.cmbOpciones = QtWidgets.QComboBox(dialogPrincipal)
        self.cmbOpciones.setGeometry(QtCore.QRect(320, 250, 201, 22))
        self.cmbOpciones.setObjectName("cmbOpciones")
        self.cmbOpciones.addItem("")
        self.cmbOpciones.addItem("")
        self.lblWebCam = QtWidgets.QLabel(dialogPrincipal)
        self.lblWebCam.setGeometry(QtCore.QRect(70, 220, 241, 161))
        self.lblWebCam.setStyleSheet("border-image: url(:/WebCam/webcam.png);")
        self.lblWebCam.setText("")
        self.lblWebCam.setObjectName("lblWebCam")
        self.lblVideo = QtWidgets.QLabel(dialogPrincipal)
        self.lblVideo.setGeometry(QtCore.QRect(70, 220, 241, 161))
        self.lblVideo.setStyleSheet("border-image: url(:/Video/video.png);")
        self.lblVideo.setText("")
        self.lblVideo.setObjectName("lblVideo")

        self.retranslateUi(dialogPrincipal)
        QtCore.QMetaObject.connectSlotsByName(dialogPrincipal)

    def retranslateUi(self, dialogPrincipal):
        _translate = QtCore.QCoreApplication.translate
        dialogPrincipal.setWindowTitle(_translate("dialogPrincipal", "Reconocimiento de Objetos"))
        self.label.setText(_translate("dialogPrincipal", "Gráficos por Computador"))
        self.label_2.setText(_translate("dialogPrincipal", "Proyecto Interciclo: Reconocimiento de objetos "))
        self.label_3.setText(_translate("dialogPrincipal", "Marzo - Agosto 2020 "))
        self.label_4.setText(_translate("dialogPrincipal", "Integrantes: Jorge Encalada y Vanessa Romero"))
        self.btnSalir.setText(_translate("dialogPrincipal", "Salir"))
        self.btnSiguiente.setText(_translate("dialogPrincipal", "Siguiente"))
        self.btnVideo.setText(_translate("dialogPrincipal", "Seleccionar"))
        self.lblRuta.setText(_translate("dialogPrincipal", "Ruta//"))
        self.cmbOpciones.setItemText(0, _translate("dialogPrincipal", "Usar la cámara del ordenador"))
        self.cmbOpciones.setItemText(1, _translate("dialogPrincipal", "Subir un video desde el ordenador"))
#import ICON_rc
#import Seleccion_rc
